### ISSUE TITLE
Multitouch and touch gestures not working.

### ISSUE THREAD

**Issue by hwchong** [sonyxperiadev/device-sony-kagura#5] opened 2017-01-19 06:21 UTC
Hi guys, this is such an awesome project. Great work open sourcing and developing an official AOSP ROM.

I just built and installed a build using commit 71f00282a967355e1fffd4c64776242fa5bce6a0 and the pinch-to-zoom and swipe gestures aren't being recognised.

**Comment by hwchong** [comment] 2017-01-20 03:53
I've found out that this happens after the screen is turned off the first time. Before the phone is put to sleep, all touch gestures are working fine.

**Comment by Ugion** [comment] 2017-10-03 16:10
Duplicate of #4, seems to be fixed

**Comment by jerpelea** [comment] 2017-10-18 12:06
please use https://github.com/sonyxperiadev/bug_tracker for future issues

**Closed as completed by jerpelea** 2017-10-18 12:06 UTC
